### ISSUE TITLE
UI Checklist

### ISSUE THREAD

**Issue by TheStress** [StudioAspen/AAAGame2023-2024#266]
#Requirements:
- [ ] (make a mock-ups of the dialogue and pause menu using the individual parts & fonts to see if they look good)
## Dialogue:
- [x] dialogue options panel
- [x] dialogue options arrow next to it
![Image](https://github.com/StudioAspen/AAAGame2023-2024/assets/36254391/fd48d3fa-40f7-4585-953c-98c88912edf8)

## Pause Menu
- [ ] back panel
- [ ] one horn (we can flip it in engine)
- [ ] doodles (each are their own image)
![Image](https://github.com/StudioAspen/AAAGame2023-2024/assets/36254391/b864eadd-afbc-4062-b17c-dce65eb4c57e)

## Slider:
- [ ] Handle
- [ ] Flatten the slider out so it can scale horizontally

## Blood Gague
- [ ] one arrow to show the point where the player is overfed
- [ ] one arrow to show the point where the player starts to lose health
![Image](https://github.com/StudioAspen/AAAGame2023-2024/assets/36254391/6d7c1eb7-36a4-438d-bcef-f00a4d537cef)
